### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by James-Eyre21** [Spiv5/CMP1903M-A01-2223#2]
### Documentation

The program includes comments to provide explanations of the code. Most methods have header comments to explain their purpose, however some processes within the methods do not have comments. This makes it more difficult to understand the code and how different methods and classes function as a whole.

### Error Handling

The program handles errors well, including range and type checks that inform the user where they made an error. If the user enters a string when the program expects a number, it will inform the user that the input was invalid and they will be asked to try again. In addition, when attempting to deal multiple cards if the user tries to deal more cards than are in the pack the program will inform them. Although, if the user asks the program to deal a number less than or equal to 0 the program will have no output for the user and simply move to the next process. This does not result in an error but may be unintuitive for the user if they do not see their mistake.

### Improvements

Overall the program is robust, well documented and functions as described in the brief. It allows users to shuffle a deck accurately, using different shuffling methods, and deal a single or a select amount of cards.

I would suggest adding more comments - mainly within the 'Card' and 'Program' classes - to further explain some processes. Also, you could make the error statement regarding entering a number below or equal to 0 more intuitive for the user.

**Comment by Spiv5** [comment]
Added comments to processes inside of methods to make code easier to understand.
Added validation for numbers less than or equal to 0 when dealing multiple cards
