### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by HamzaH042** [Spiv5/CMP1903M-A01-2223#3]
Documentation- The program has been commented well and almost all the code used has comments to explain the purpose of it. The comments explains the work very well. There are some parts of the comments that can be made simpler and easier to understand.

Error Handling- there is good error handling in this program, when the user enters a string instead of an integer you are given the correct error. this is the same if the integer entered is too small or isn't valid it informs the user.

improvements- Overall the program is well designed and simple to use, it fits the intended purpose and allows the user to operate and use the program fairly simply. The comments made could be made simpler to understand and also more could be added to make things run smoothly and easier when reviewing. This could be done by explaining in more detail the precise functions rather than a brief explanation.

**Comment by Spiv5** [comment]
Improved readability of the comments by simplifying the language, and added extra comments to explain some sections more indepth
